### ISSUE TITLE
Write a Fraggin' Paper!

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#1]

**Comment by sixtyfive** [comment]
These issues are about the bigger-picture stuff that we're still so challenged by: #25, #17, #4.

**Comment by sbukhar1** [comment]
Here's a little info about the aaya's Franzi has chosen. Looks like they were aayas that could be easily misinterpreted when approached with rationalist and orthodox thinking. Amongst these misinterpreted aayas there are certain trends like thematical threads, metaphorical elements, supernatural features. (jinns i. e.)

Forwarded Message from Franzi:
The Ayahs were pretty much chosen by the author Goldziher and it was all about rationalist and orthodox (and apologetic)  thinking which led to misleading and (for what we want to find out many words and over-detailed (is that a word?) ) words and interpretation.
some ayahs share thematical threads, like metaphorical elements, supernatural features (jinns i. e.)

**Comment by sixtyfive** [comment]
Sounds like it's not too useful to us right now?

**Comment by sixtyfive** [comment]
Okay, except for the overdetailed (let's declare that a word) thing. So let's see what comes out of looking at _all_ the Aayas numbers, if it confirms Goldziher or if it collides with him...

**Comment by FranziskaBlunck** [comment]
yes, and maybe figuring out "favourite" and pointing out "written most
about" ayas for every author. i or we could then go into a deeper context
analyses and finding out "trends" in the intellectual approach for every or
some special authors. (by really reading the ayas they tafaseert about)

or?
