### ISSUE TITLE
Get going with Rnotebook/Rmarkdown and report back (enlightenment or frustration?)

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#15]
Please check whether it works for you!
Did you find the Rmarkdown cheatsheet and does the preview work?

**Comment by FranziskaBlunck** [comment]
pretty much enlightment though still work

**Comment by sixtyfive** [comment]
ah wonderful! github comments!

please go ahead and add the chapter you wrote on one of the mufassirun into the paper at the appropriate place, commit and push.

**Comment by FranziskaBlunck** [comment]
IIIIII want to, but my shitty windows system not, still on console with git
pull upstream_sixtyfive master

2016-11-24 23:53 GMT+01:00 J. R. Schmid <notifications@github.com>:

**Comment by sixtyfive** [comment]
o_O

at what time did you start the pull? how many minutes has it been?

**Comment by FranziskaBlunck** [comment]
ich sehe in meiner console keine metadaten, kein plan

2016-11-25 0:00 GMT+01:00 J. R. Schmid <notifications@github.com>:

**Comment by sixtyfive** [comment]
Since you pushed earlier, the pull has had to work, too. So were you able to play around with Rnotebook yet?
