### ISSUE TITLE
Make sure Zotero sync works

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#16]
Did you guys get the Zotero invite I sent you?

**Comment by sixtyfive** [comment]
@thomkeppen Btw, are you getting these messages here on GitHub/Waffle?

**Comment by sixtyfive** [comment]
@thomkeppen, @sbukhar1, please respond to this, too! Right now there's confusion and frustration, but eventually there'll be a sound idea and at that time it'd be helpful if we hit the ground running in terms of having everything in place for writing  up findings.

**Comment by thomkeppen** [comment]
I am

**Comment by sbukhar1** [comment]
I also accepted the Zotero invite. Is this what you were wondering ??

**Comment by sixtyfive** [comment]
Ah then it didn't send emails out for that. Sorry for the nagging. So you're both seeing our group in the Zotero client and the works that are already added to it?

**Comment by thomkeppen** [comment]
The suggested readings?

**Comment by sbukhar1** [comment]
No problem man nagging is needed at this point. Also I am able to see the sources updated yesterday. Do you think it is necessary to cited the tutorial paged for sqlite??

**Comment by sixtyfive** [comment]
You can see it as suggested readings if you like. What it's supposed to be is an inventory of all documents we made use of so that the paper's bibliography can automatically be built from it.

So far I put one technical paper (the documentation on the `topicmodel` package) and 3 works by Ignac Goldziher in there. They're probably interesting for real, but mainly it's important that we all see them in the Zotero client. If that works I'll be a happy beaver.

**Comment by sixtyfive** [comment]
@sbukhar1 Kewl man! Nah, I'd say programming language docs or tutorials are too basic to be quoted in a scientific paper. If we decide to use a very specific package (like @thomkeppen did when he chose `topicmodel`) then it's probably warranted.

**Comment by sixtyfive** [comment]
@sbukhar1 but ofc the fact that we put the corpus into sqlite to poke and prod it another way is something that needs to be mentioned in the paper under https://github.com/sixtyfive/hw/blob/master/tafaseer_group/results/Paper.Rmd#12-data-extraction-and-transformation-into-processable-outer-form or possibly under https://github.com/sixtyfive/hw/blob/master/tafaseer_group/results/Paper.Rmd#2-analysis

**Comment by thomkeppen** [comment]
I can see all of that

**Comment by sixtyfive** [comment]
Awesome! Moving this far to the right!
