### ISSUE TITLE
Are we interested in comparing Muʿtazilite and Orthodox thinking?

### ISSUE THREAD

**Issue by FranziskaBlunck** [sixtyfive/hw#17]
What it is all about? 
Do they really share a bias towards this huge surge of words regarding topics in the qur'an that fall under unattainable knowledge, superstitious stories, metaphors??
(Trying to get Goldziher of my back)

**Comment by sixtyfive** [comment]
@FranziskaBlunck, can you explain a little to the rest of us? What problem does Goldziher pose? Has this to do with the info Sarosh or I got you, and if so, what numbers ("surge of words") do you refer to?

**Comment by sixtyfive** [comment]
There's a guy here who left al-Azhar University to come to Leipzig for his PHDs because he's pretty sure they would have landed in jail there or worse. His PHD thesis is on the Muʿtazila and I think he's trying to show their thinking would make for a better foundation for modern, liberal, progressive Islamic practice today. I'll try to meet him after Friday prayers and ask him for a little interview. *What questions do you want me to ask him*?

**Comment by thomkeppen** [comment]
Who is Al-Tabari and what is the Quran?

**Comment by thomkeppen** [comment]
Why would they be more liberal?  Emphasis on reason?

**Comment by sixtyfive** [comment]
Lol okay, noted! (Not sure if the lol is appropriate - you sound serious). As for the second: I *think* he once said something towards that effect, yes. Not sure though if he really thinks that they were or if he just wants to use them to build foundations for a more liberal Islam. I'll ask all three questions if the meeting works out.

**Comment by sbukhar1** [comment]
Thats actually pretty cool this man must have a good grasp on Quranic
theology. Ask that man what specific topics differentiate the most in terms
of liberal and conservative theology. Like what topics (or if possible
specific aayas) do the two theologies have polar opposite interpretations.
Also Ask (if possible) What lend to such different interpretations ? (
after all they are looking at the same exact text down to the letter)
possibly the different schools of thoughts or perhaps liberal theologist
are hip to fact checking information via internet/google.

**Comment by sixtyfive** [comment]
Yeah I guess he must, but then he's also a bit of a diva. I'll try though! Questions noted down!

**Comment by sixtyfive** [comment]
@sbukhar1 Hmm, can you clarify your last sentence a little? Was that a question or a suggestion?
