### ISSUE TITLE
Please all git pull! (I did, I think Thom did, so you can move this to "Done" when you did, Sarosh)

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#18]
Franzi did a rather large push. I've pulled it, merged it, and pushed it back to my Github. Thom and Sarosh, please do `git pull upstream_sixtyfive`. If that gives any "CONFLICT" messages you don't know how to resolve, please keep console window open and send me a screenshot!

**Comment by sixtyfive** [comment]
@sbukhar1 please respond! did that work?

**Comment by sbukhar1** [comment]
yes I was able successfully git pull

**Comment by sixtyfive** [comment]
Cheers!!!
