### ISSUE TITLE
We need to decide how to proceed with TM

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#20]
To give you an idea just how compute intensive it is: it took 55000 seconds to do the TM for the first 4 books, that's 15 hours. If you compare the other books' file sizes to those, you can guesstimate total time. I might  be able to make that twice as fast but would rather not to keep quality if living reasonable for Thom. I propose to go to 90+140/2=115 topics (theoretical generic optimum in terms of usefulness) and let TM run on at most 4 books, maybe 2 pairs, not sure. What are everyone's thoughts? Please all comment!

**Comment by sixtyfive** [comment]
And as of this morning: "Execution for ../../corpora/altafsir_com/processed/plain/nohadith/002-011.txt starts at 124738s" (34 hours)

**Comment by thomkeppen** [comment]
Sounds good

**Comment by sixtyfive** [comment]
Decisions from today's meeting led to #21, #23.
