### ISSUE TITLE
Evaluate TM results

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#21]
Please find them at http://altafsir_com.iw20.weitnahbei.de/analyses/other/ (all the files containing "LDAGibbs" in their names basically)

**Comment by sixtyfive** [comment]
btw any progress on this? did the ISIS guy help?

**Comment by thomkeppen** [comment]
It's all confusing.  Trying to read about different methods

**Comment by thomkeppen** [comment]
Most techniques are designed to display topic frequency across a number of
texts. We have 18 unique topics for each text.

We can still do something though

**Comment by sixtyfive** [comment]
the ISIS guy's method looked like it would at least give a visual view (sorry, bad phrasing) of the data that plopped out of that huge TM run...

**Comment by thomkeppen** [comment]
I'll go back to his page

**Comment by sixtyfive** [comment]
here's the link again: https://rpubs.com/cosmopolitanvan/topicmodelling ... i'll delete the other waffle as it's a duplicate. not sure if we're calling these things waffles or issues or tickets or what.
