### ISSUE TITLE
Run TM on both pairs of texts Thom mentioned

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#22]
Can you link me to the files, Thom?

**Comment by sixtyfive** [comment]
nm thom i take it you mean the ones you added to the repo

**Comment by thomkeppen** [comment]
Sorry I missed this at first.

Yeah I meant the two histories I found on open arabic. But it seems like
Maxim thinks the Ibn Kathir Al-Tabari concept is untenable.

**Comment by sixtyfive** [comment]
:(

**Comment by thomkeppen** [comment]
I know

**Comment by sixtyfive** [comment]
hmm at least not too bad then that i didn't get around to doing this yet...

i'm unfortunately so boggled down in work right now that i can't do research about scholarly work on tafaseer. i did find some English works by Ignac Goldziher though and put their names into the Zotero group. did you get the invite for that?

it sucks but right now it looks like there's no point in further TM runs, not before we were able to look at some numbers and charts from other methods, esp. the new stylo runs and the first TM run and the amounts-of-work-per-quran-part stuff @sbukhar1 is doing.
