### ISSUE TITLE
What scholarly work is there that could help us?

### ISSUE THREAD

**Issue by sixtyfive** [sixtyfive/hw#4]
Did you notice how there's a whole world of scientific papers with titles starting with "Towards a ..." whenever they know they've bitten off more than they could chew? Ours could be "Towards a corpus linguistical criticism of non-digital Quran exegetic work" or something :)

**Comment by sixtyfive** [comment]
@FranziskaBlunck Would you prefer single Waffle tickets per scholarly-work-topic like the one you opened on Muatazilite thinking or should we keep the whole scholarly-work-discussion in one ticket? In any case, I'm moving this here to the "in progress" section.

**Comment by sixtyfive** [comment]
Btw did you notice how there's a whole world of scientific papers with titles starting with "Towards a ..." whenever they know they've bitten off more than they could chew? Ours could be "Towards a corpus linguistical criticism of non-digital Quran exegetic work" or something :)

**Comment by sbukhar1** [comment]
kopy

**Comment by thomkeppen** [comment]
جميل

**Comment by sixtyfive** [comment]
Okay that was tongue-in-cheek but glad if you like it :-P.

So let's collect some scholarly work! I found this here and I think the title sounds very promising: _Scientific Exegesis of the Qur'an_. The author's name is Zafar Ishaq Ansari. Unfortunately I can't seem to get access from our University's network. It was published in 	Journal of Qur'anic Studies, University of Edinburgh, 2001. Anyone have more luck??

**Comment by FranziskaBlunck** [comment]
*Scientific **Exegesis** of the **Qur'an*.

is that the one?

Am 01.12.2016 3:20 vorm. schrieb "J. R. Schmid" <notifications@github.com>:

**Comment by sixtyfive** [comment]
"The one"? As in, Neo, The Matrix? At least it's the same link. Do you have a PDF, etc.?

**Comment by FranziskaBlunck** [comment]
oh, was there no pdf attachment on the email cause it is shown that i send
you the pdf..

Am 01.12.2016 4:28 nachm. schrieb "J. R. Schmid" <notifications@github.com>:

"The one"? As in, Neo, The Matrix? At least it's the same link. Do you have
a PDF, etc.?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/sixtyfive/hw/issues/4#issuecomment-264202919>, or mute
the thread

**Comment by sixtyfive** [comment]
Sorry, I haven't received any file :(
Could you perhaps link to it?

**Comment by FranziskaBlunck** [comment]
there you go
http://www.jstor.org/action/doAdvancedResults?acc=off&q0=sn%3A1465-3591&c1=AND&q1=vo%3A3&c2=AND&q2=no%3A1&c3=AND&q3=sp%3A91

**Comment by sixtyfive** [comment]
@thomkeppen @sbukhar1 Might be something for the lit review?
